---

- hosts: local
  become: yes
  become_user: root
  roles:
    - common-packages
    - etc-hosts
    - ssh-forward
    - oh-my-zsh
    - nginx
    - php
    - composer
    - mysql
    - postgresql
    - rabbitmq-management
    - sass
    - nodejs
    - logstash
  vars_files:
    - vars.yml
    - vars.local.yml
